# meta.yaml
package:
  name: pankegg
  version: "0.1"

source:
  path: .

build:
  noarch: python
  script: python setup.py install

requirements:
  host:
    - python
    - pip
  run:
    - python
    - flask
    - pandas
    - numpy
    - scikit-learn
    - scipy

test:
  imports:
    - panKEGG.panKEGG_app.main
    - panKEGG.panKEGG_db_cook.main

about:
  home: https://github.com/Avanbelle/PanKEGG.git
  license: MIT
  summary: Application PanKEGG
